BEGIN;
DROP TABLE IF EXISTS CLIENTS_RETURN      CASCADE;
DROP TABLE IF EXISTS PRODUCTS_SOLD       CASCADE;
DROP TABLE IF EXISTS SALES               CASCADE;
DROP TABLE IF EXISTS PRODUCTS_DELIVERIES CASCADE;
DROP TABLE IF EXISTS DELIVERIES          CASCADE;
DROP TABLE IF EXISTS STORE_STATUS        CASCADE;
DROP TABLE IF EXISTS SUPPLIERS           CASCADE;
DROP TABLE IF EXISTS PRICE_HISTORY       CASCADE;
DROP TABLE IF EXISTS PARAMETER_PRODUCTS  CASCADE;
DROP TABLE IF EXISTS POSSIBLE_PARAMETERS CASCADE;
DROP TABLE IF EXISTS PRODUCTS            CASCADE;
DROP TABLE IF EXISTS PARAMETERS          CASCADE;
DROP TABLE IF EXISTS CATEGORIES          CASCADE;
DROP TABLE IF EXISTS BRAND               CASCADE;

DROP FUNCTION IF EXISTS returned_check()                        CASCADE;
DROP FUNCTION IF EXISTS allowed_param_check()                   CASCADE;  
DROP FUNCTION IF EXISTS update_decrease_store_status()          CASCADE;
DROP FUNCTION IF EXISTS update_increase_store_status()          CASCADE;
DROP FUNCTION IF EXISTS insert_id_products_to_store_status()    CASCADE;  

COMMIT;
